# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbouhier <mbouhier@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/27 10:53:48 by mbouhier          #+#    #+#              #
#    Updated: 2016/02/29 00:16:06 by mbouhier         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FLAGS = -Werror -Wextra -Wall

SRCS_PATH = ./
INCLUDES_PATH = ../includes/
OBJ_PATH = ../obj/


SRCS_NAME = ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
		   ft_isdigit.c ft_isprint.c ft_itoa.c ft_lstadd.c ft_lstdel.c \
		   ft_lstdelone.c ft_lstiter.c ft_lstmap.c ft_lstnew.c ft_memalloc.c \
		   ft_memccpy.c ft_memchr.c ft_memcpy.c ft_memdel.c ft_memmove.c \
		   ft_memcmp.c ft_memset.c ft_putchar.c ft_putchar_fd.c ft_putendl.c \
		   ft_putendl_fd.c ft_putnbr.c ft_putnbr_fd.c ft_putstr.c \
		   ft_putstr_fd.c ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c \
		   ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c ft_striter.c \
		   ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c \
		   ft_strmapi.c ft_strncat.c ft_strncmp.c ft_strncpy.c ft_strnequ.c \
		   ft_strnew.c ft_strnstr.c ft_strrchr.c ft_strsplit.c ft_strstr.c \
		   ft_strsub.c ft_strtrim.c ft_tolower.c ft_toupper.c get_next_line.c \
		   ft_abs.c\

SRCO = $(SRCS_NAME:.c=.o)

SRC = $(addprefix $(SRCS_PATH), $(SRCS_NAME))
INC = $(addprefix -I, $(INCLUDES_PATH))
OBJ = $(addprefix $(OBJ_PATH), $(SRCO))

all : $(NAME)

$(NAME) :
		@echo "\033[2J"
		@echo "\033[100A"
		@echo "\033[32m   __    ____ ___   ____ ______"
		@echo "  / /   /  _// _ ) / __//_  __/"
		@echo " / /__ _/ / / _  |/ _/   / /   "
		@echo "/____//___//____//_/    /_/    "
		@echo "                               "
		@echo " MAKE ALL \033[0m"
		@sleep 0.1
		@gcc $(FLAGS) $(INC) -c $(SRC)
		@ar rc $(NAME) $(SRCO)
		@ranlib $(NAME)

clean :
		@rm -f $(SRCO)
		@echo "\033[2J"
		@echo "\033[100A"
		@echo "\033[31m   __    ____ ___   ____ ______"
		@echo "  / /   /  _// _ ) / __//_  __/"
		@echo " / /__ _/ / / _  |/ _/   / /   "
		@echo "/____//___//____//_/    /_/    "
		@echo "                               "
		@echo " MAKE CLEAN \033[0m"
		@sleep 0.1

fclean : clean
		@rm -f $(NAME)
		@echo "\033[2J"
		@echo "\033[100A"
		@echo "\033[34m   __    ____ ___   ____ ______"
		@echo "  / /   /  _// _ ) / __//_  __/"
		@echo " / /__ _/ / / _  |/ _/   / /   "
		@echo "/____//___//____//_/    /_/    "
		@echo "                               "
		@echo " MAKE FCLEAN \033[0m"
		@sleep 0.1
		

re : fclean all
		@echo "\033[2J"
		@echo "\033[100A"
		@echo "\033[36m   __    ____ ___   ____ ______"
		@echo "  / /   /  _// _ ) / __//_  __/"
		@echo " / /__ _/ / / _  |/ _/   / /   "
		@echo "/____//___//____//_/    /_/    "
		@echo "                               "
		@echo " MAKE RE \033[0m"
		@sleep 0.1


.PHONY : all re fclean clean
